/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDerivCallbackRouteImport } from './routes/auth.deriv-callback'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedStrategyLabRouteImport } from './routes/_authenticated/strategy-lab'
import { Route as AuthenticatedMt5DirectRouteImport } from './routes/_authenticated/mt5-direct'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBotsRouteImport } from './routes/_authenticated/bots'
import { Route as AuthenticatedBacktestRouteImport } from './routes/_authenticated/backtest'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as ApiPublicHooksBotLoopRouteImport } from './routes/api/public/hooks/bot-loop'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDerivCallbackRoute = AuthDerivCallbackRouteImport.update({
  id: '/deriv-callback',
  path: '/deriv-callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStrategyLabRoute =
  AuthenticatedStrategyLabRouteImport.update({
    id: '/strategy-lab',
    path: '/strategy-lab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMt5DirectRoute = AuthenticatedMt5DirectRouteImport.update({
  id: '/mt5-direct',
  path: '/mt5-direct',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotsRoute = AuthenticatedBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBacktestRoute = AuthenticatedBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const ApiPublicHooksBotLoopRoute = ApiPublicHooksBotLoopRouteImport.update({
  id: '/api/public/hooks/bot-loop',
  path: '/api/public/hooks/bot-loop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/backtest': typeof AuthenticatedBacktestRoute
  '/bots': typeof AuthenticatedBotsRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/mt5-direct': typeof AuthenticatedMt5DirectRoute
  '/strategy-lab': typeof AuthenticatedStrategyLabRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/deriv-callback': typeof AuthDerivCallbackRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/hooks/bot-loop': typeof ApiPublicHooksBotLoopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/backtest': typeof AuthenticatedBacktestRoute
  '/bots': typeof AuthenticatedBotsRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/mt5-direct': typeof AuthenticatedMt5DirectRoute
  '/strategy-lab': typeof AuthenticatedStrategyLabRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/deriv-callback': typeof AuthDerivCallbackRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/hooks/bot-loop': typeof ApiPublicHooksBotLoopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/backtest': typeof AuthenticatedBacktestRoute
  '/_authenticated/bots': typeof AuthenticatedBotsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/mt5-direct': typeof AuthenticatedMt5DirectRoute
  '/_authenticated/strategy-lab': typeof AuthenticatedStrategyLabRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/deriv-callback': typeof AuthDerivCallbackRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/hooks/bot-loop': typeof ApiPublicHooksBotLoopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/backtest'
    | '/bots'
    | '/chat'
    | '/dashboard'
    | '/memory'
    | '/mt5-direct'
    | '/strategy-lab'
    | '/api/chat'
    | '/auth/deriv-callback'
    | '/chat/$threadId'
    | '/api/public/hooks/bot-loop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/backtest'
    | '/bots'
    | '/chat'
    | '/dashboard'
    | '/memory'
    | '/mt5-direct'
    | '/strategy-lab'
    | '/api/chat'
    | '/auth/deriv-callback'
    | '/chat/$threadId'
    | '/api/public/hooks/bot-loop'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/backtest'
    | '/_authenticated/bots'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/memory'
    | '/_authenticated/mt5-direct'
    | '/_authenticated/strategy-lab'
    | '/api/chat'
    | '/auth/deriv-callback'
    | '/_authenticated/chat/$threadId'
    | '/api/public/hooks/bot-loop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicHooksBotLoopRoute: typeof ApiPublicHooksBotLoopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/deriv-callback': {
      id: '/auth/deriv-callback'
      path: '/deriv-callback'
      fullPath: '/auth/deriv-callback'
      preLoaderRoute: typeof AuthDerivCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/strategy-lab': {
      id: '/_authenticated/strategy-lab'
      path: '/strategy-lab'
      fullPath: '/strategy-lab'
      preLoaderRoute: typeof AuthenticatedStrategyLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mt5-direct': {
      id: '/_authenticated/mt5-direct'
      path: '/mt5-direct'
      fullPath: '/mt5-direct'
      preLoaderRoute: typeof AuthenticatedMt5DirectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bots': {
      id: '/_authenticated/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof AuthenticatedBotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtest': {
      id: '/_authenticated/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof AuthenticatedBacktestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/public/hooks/bot-loop': {
      id: '/api/public/hooks/bot-loop'
      path: '/api/public/hooks/bot-loop'
      fullPath: '/api/public/hooks/bot-loop'
      preLoaderRoute: typeof ApiPublicHooksBotLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBacktestRoute: typeof AuthenticatedBacktestRoute
  AuthenticatedBotsRoute: typeof AuthenticatedBotsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedMt5DirectRoute: typeof AuthenticatedMt5DirectRoute
  AuthenticatedStrategyLabRoute: typeof AuthenticatedStrategyLabRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBacktestRoute: AuthenticatedBacktestRoute,
  AuthenticatedBotsRoute: AuthenticatedBotsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedMt5DirectRoute: AuthenticatedMt5DirectRoute,
  AuthenticatedStrategyLabRoute: AuthenticatedStrategyLabRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthDerivCallbackRoute: typeof AuthDerivCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDerivCallbackRoute: AuthDerivCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiPublicHooksBotLoopRoute: ApiPublicHooksBotLoopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
